### ISSUE TITLE
Inverse the behavior of the Heading's top margin from theme

### ISSUE THREAD

**Issue by bfintal** [gambitph/Stackable#2190] opened 2022-03-01 06:21 UTC
![image](https://user-images.githubusercontent.com/1033611/158323741-4b119173-1cd7-43c3-9904-43081b1e8253.png)

**Comment by andeng1106** [comment] 2022-11-08 06:58
@bfintal This is confirmed as fixed now and will mark this as "For Merging" but not yet ready to merge PR since ongoing performance enhancement testing.

**Closed** 2023-01-17 10:09 UTC
Labels: bug, [block] Heading
