### ISSUE TITLE
Preview glitch when trying to transform image block to image box block

### ISSUE THREAD

**Issue by bfintal** [gambitph/Stackable#1918] opened 2021-10-15 15:54 UTC
Possible cause is that the preview cannot be generated.

https://user-images.githubusercontent.com/1033611/137516948-d3d8aa2a-3915-4022-95f5-c001cad6bfdf.mp4

**Comment by blankart** [comment] 2021-10-22 04:51
Duplicate of #1917

**Closed by blankart** 2021-10-22 04:51 UTC
Labels: bug, [version] V3
