### ISSUE TITLE
Heading / Text block parent hover state not working

### ISSUE THREAD

**Issue by bfintal** [gambitph/Stackable#1748] opened 2021-10-03 07:36 UTC
1. Add a card
2. In the title, change the heading color when the hover state is parent-hovered

We probably need to check other blocks if they're working.

The way to check is to set the transition duration in `src/styles/block-transitions.scss` temporarily to `2s`

**Comment by blankart** [comment] 2021-10-04 01:41
Duplicate of #1736

**Closed by blankart** 2021-10-04 01:41 UTC
Labels: bug, high priority, [version] V3, [block] Text, [block] Heading
