### ISSUE TITLE
unexpected or invalid content message

### ISSUE THREAD

**Issue by BillMoriarty** [gambitph/Stackable#71] opened 2019-03-09 18:59 UTC
Hi,
I’m finding the following bug another person noticed "Many times I will add a new block to a page and everything works great. Come back later to edit the page again and the block I just added will have the message"

Once they are “invalid” they are not editable. So I need to make a new block and recreate it all again.

Here are 4 screenshots. After changing nothing, then coming back to the site you’ll see they are “invalid”
https://drive.google.com/file/d/1JxPTswNaGHkv1Y4PprEzWeHPH8hGGnj7/view?usp=sharing

If I select a block to try and edit it the right sidebar shows no edit controls
https://drive.google.com/file/d/1OmBY0Fxv79Ul2NGD0fLngH-ImRfaNbj3/view?usp=sharing

If I click “resolve” this is what appears.
https://drive.google.com/file/d/1nuEo8SWl8RapHpCH_cYAhSxMX1mVpqr0/view?usp=sharing

If I then click “convert to block” this is what happens
https://drive.google.com/file/d/1f7ai48yuYOvLni8Yp63eb8HpDFiwkvU6/view?usp=sharing

otherwise, these are nice to work with.
Thanks
Bill

**Comment by bfintal** [comment] 2019-03-14 07:52
Hey @BillMoriarty can you post your content here or steps to reproduce this?

**Comment by dtmpsc** [comment] 2019-03-15 22:05
same here, this is very frustrating. As long as you don't edit it, it still works as normal.

**Comment by BillMoriarty** [comment] 2019-03-18 02:37
@bfintal sure thing. I am about to make a new block now.

Here is the new block. No problems yet...
https://drive.google.com/open?id=11esRlI4p2TKYHeVycX3h85ezWCe5bd_S

For reference, on this same page as I'm adding a new block, here's a typical old block which is invalid.
https://drive.google.com/open?id=1mgSlAFQebLaoW1stKYHU2K4NwTNegE1i

Here is my new block a minute later after I add my content and hit Update. No problems.
https://drive.google.com/open?id=1qbRDK03dE3BXJLytDLXJLI18nOVfLS3h

I wait a minute or two, hit refresh on my browser and...my new block is now invalid.
https://drive.google.com/open?id=1bQLRrueQTdFuRAkBRalpIqvQfamWzlVu

thanks for any help
-Bill

**Comment by BillMoriarty** [comment] 2019-03-21 00:25
@bfintal is there any other info I can provide? Thanks!

**Comment by mcclister** [comment] 2019-04-02 01:12
I have the same problem on a client site with the image blocks. Works great, and then when I come back in through the editor it gives that error message.  The weird thing is, if I go to resolve block, the current and 'after conversion code' are exactly the same.

I went through testing block options one by one, and for the image block it looks like selecting open link in new tab is what causes the issue.

**Comment by yssagambit** [comment] 2020-02-20 07:46
this may have been fixed by version 2.2 already.

**Closed by yssagambit** 2020-02-20 07:46 UTC
Labels: bug, need more info
