### ISSUE TITLE
Blocks automatically have a set margin-left value when added

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1107] opened 2021-03-15 06:45 UTC
When using the Stackable theme,
added blocks that has the Block Background turned on will have a margin-left value of `calc( 50% - 50vw )` in Frontend.
upon checking, This value is coming from the stackable theme 
<img width="367" alt="Screen Shot 2021-03-15 at 2 35 51 PM" src="https://user-images.githubusercontent.com/28699204/111113320-8f452d80-859c-11eb-9bf1-5d0f5d252b50.png">

steps:
1. activate the stackable theme
2. in a new page, add a header block
3. turn the block background on, & set the block to Full Width

in frontend:
<img width="1680" alt="Screen Shot 2021-03-15 at 2 42 45 PM" src="https://user-images.githubusercontent.com/28699204/111113642-0d093900-859d-11eb-83f6-0c5ef8bb87e6.png">

**Comment by blankart** [comment] 2021-03-15 07:05
Closing this issue. Duplicate of #1073

**Closed by blankart** 2021-03-15 07:05 UTC
Labels: bug
