### ISSUE TITLE
Testimonial block duplicating Name text under Image

### ISSUE THREAD

**Issue by ruhusudk** [gambitph/Stackable#860] opened 2020-08-30 22:30 UTC
**Describe the bug**
The testimonial block is duplicating the Name text. Whatever is inserted as the "Name" text shows up twice. The additional text, which shouldn't show up, is in an arbitrary font as well. In the HTML it shows that text as "alt" and attempting to delete from the HTML breaks the block in Gutenberg. When the "Image" is turned off under Style, then the "Name" text isn't duplicated. 

**To Reproduce**
1. Go to https://kurani.us/howard-west/
2. Scroll 1/3 way down the page til you reach the Testimonial block on left side of page

**Expected behavior**
This block was working fine until yesterday. It typically shows the name once and in the correct font. 

**Screenshots**
<img width="1438" alt="Screen Shot 2020-08-30 at 6 18 20 PM" src="https://user-images.githubusercontent.com/70491102/91670796-bfd8e480-eaee-11ea-9fe0-96d14b7691a3.png">
<img width="447" alt="Image 2020-08-30 at 9 57 44 AM" src="https://user-images.githubusercontent.com/70491102/91670801-cbc4a680-eaee-11ea-9ba1-c3d25c471ca1.png">

**Desktop:**
 - OS: MacOS
 - Browser: Safari
 - Browser Version: 13.1.2

**Smartphone:**
 - Device: iPhoneX
 - OS: iOS 13.6.1
 - Browser: Safari, Chrome

**Comment by bfintal** [comment] 2020-09-01 02:52
Thanks for the report.

Confirmed this is happening when you change the formatting of the name. e.g. make a word in there bold. The error is caused by the name field being used as an `alt` tag for the block image.

**Comment by bfintal** [comment] 2020-09-03 03:37
Fixed by 26176f376e159eb5cf41f8ce4f253122e76c324f

**Closed by bfintal** 2020-09-03 03:37 UTC
Labels: bug, high priority
