### ISSUE TITLE
Anchor links on Tabs block

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#3128] opened 2024-04-02 06:51 UTC
**Is your feature request related to a problem? Please describe.**
Yes. Users want to be able to create HTML anchors on the tabs in Tabs block and upon clicking a link with the HTML anchor, they easily navigate to the said tab.
Reference: https://www.facebook.com/groups/wpstackable/posts/1412951582926684/

**Describe the solution you'd like**
To be able to open/navigate to the tab by clicking the HTML anchor link from tabs.

**Describe alternatives you've considered**
N/A

**Comment by bfintal** [comment] 2024-04-03 06:38
Duplicate of [#3067](https://github.com/gambitph/Stackable/issues/3067)

**Closed as completed by bfintal** 2024-04-03 06:38 UTC
Labels: enhancement, [block] Tabs
