### ISSUE TITLE
Add full height option from V2

### ISSUE THREAD

**Issue by prconcepcion** [gambitph/Stackable#2232] opened 2022-04-07 23:16 UTC
V2 Container Block had a dropdown wherein you can change the height. 

![image](https://user-images.githubusercontent.com/49634311/162334521-659874cb-3c9e-4bb8-a91a-a8a0ede24920.png)

**Comment by andeng1106** [comment] 2022-05-31 08:57
Duplicate of https://github.com/gambitph/Stackable/issues/2256

**Closed** 2022-05-31 09:01 UTC
Labels: enhancement, V3 Migration
