### ISSUE TITLE
Featured Image doesn't work inside a Query Loop

### ISSUE THREAD

**Issue by bfintal** [gambitph/Stackable#1754] opened 2021-10-04 01:13 UTC
1. Add a Query Loop block
2. Add a column
3. In the column settings, enable container background, and pick the background image as dynamic content > Current Post > Featured Image

or

1. Add a Query Loop block
2. Add an adv image block
3. Pick the image as dynamic content > Current Post > Featured Image

Image won't show up in the backend and frontend

**Comment by blankart** [comment] 2021-10-04 01:42
Duplicate of #1577

**Closed by blankart** 2021-10-04 01:42 UTC
Labels: bug, high priority, Dynamic Content, [version] V3
