### ISSUE TITLE
feature image leaks out of the shape when the stretch option is turned off on edge browser [v2][edge][feature]

### ISSUE THREAD

**Issue by mico97** [gambitph/Stackable#305] opened 2019-10-17 10:23 UTC
only affects the edge browser, firefox and chrome are working as intended. additionally, for the circle and blob shapes, the image leaks out of the shape when the stretch option is turned off. 

the initial issue is a duplicate of  #258.
 
![featureimg](https://user-images.githubusercontent.com/50035760/67000766-0017ba00-f10b-11e9-9fe7-6285c4cc17f5.png)

**Comment by bfintal** [comment] 2019-10-18 01:00
Duplicate of #251

**Closed by bfintal** 2019-10-18 01:00 UTC
Labels: [block] all blocks, [version] V2, bug, duplicate
